#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -no-fullscreen -show drun -location 1 -xoffset 0 -yoffset 30 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme
